version: '3'

services:
  redis:
    image: redis:7.0
    container_name: crawlers-redis
    volumes:
      - redis-data:/data
      - ./redis-conf/:/usr/local/etc/redis/
      - ./redis-logs:/logs
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - crawlers
    env_file:
      - .env
  
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - '8001:8001'
    volumes:
      - ./redisinsight-data:/db
    networks:
      - crawlers

  mongo:
    image: mongo:4.2
    container_name: crawlers-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - crawlers

  mongo-express:
    image: mongo-express
    container_name: crawlers-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
    networks:
      - crawlers

  

volumes:
  redis-data:
  mongo-data:

networks:
  crawlers:
    driver: bridge